version: '3.9'

services:
  logtowa-app:
    container_name: logtowa-app
    image: tobiaswaelde/logtowa-app:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      APP_TITLE: LogTowa # optional
      API_BASE_URL: http://localhost:3001
      API_TOKEN: secret
      SOCKET_TOKEN: secret
