// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly DEBUG_LOADING_DELAY: string;
  readonly APP_TITLE: string;
  readonly API_BASE_URL: string;
  readonly API_TOKEN: string;
  readonly SOCKET_TOKEN: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
